permalink: /:categories/:title/
exclude: ["assets/styles/sass/", "CNAME", "Rakefile"]
auto: true
markdown: kramdown

name: "Aniket Pant"
tagline: "Rawrrr"
description: "Notes and Essays by a developer"
author:
 name: "Aniket Pant"
 email: "me@aniketpant.com"
 github: "aniketpant"
 twitter: "aniket_pant"
 facebook: "aniket.pant"