permalink: /:categories/:title
auto: true
markdown: kramdown
exclude: Rakefile, CNAME, sass/, script/, README.md

url: http://aniketpant.com

name: "Aniket Pant"
tagline: "Rawrrr!"
description: "Notes and Essays by a developer"
author:
 name: "Aniket Pant"
 email: "me@aniketpant.com"
 github: "aniketpant"
 twitter: "aniket_pant"
 facebook: "aniket.pant"